"""empty message

Revision ID: 39dea0982bab
Revises: 86af2f9a85a2
Create Date: 2019-01-22 09:52:16.942031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dea0982bab'
down_revision = '86af2f9a85a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=5), nullable=False),
    sa.Column('amount_money', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('number_invoice_provider', sa.String(length=5), nullable=False),
    sa.Column('number_invoice_reciever', sa.String(length=5), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['status_operation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    # ### end Alembic commands ###
