"""empty message

Revision ID: 86af2f9a85a2
Revises: 8daf13b0c5dd
Create Date: 2019-01-22 09:45:31.007364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86af2f9a85a2'
down_revision = '8daf13b0c5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_operation')
    # ### end Alembic commands ###
