"""empty message

Revision ID: a982f34ef1ea
Revises: 10e750f547e8
Create Date: 2019-01-24 15:18:13.643012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a982f34ef1ea'
down_revision = '10e750f547e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('payment_confirm_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'payment_confirm_code')
    # ### end Alembic commands ###
