"""empty message

Revision ID: a9c9b4bb783d
Revises: ff2b240c47ed
Create Date: 2019-01-25 11:02:49.921330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c9b4bb783d'
down_revision = 'ff2b240c47ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payment_invoice_provider'), 'payment', ['invoice_provider'], unique=False)
    op.create_index(op.f('ix_payment_invoice_reciever'), 'payment', ['invoice_reciever'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_invoice_reciever'), table_name='payment')
    op.drop_index(op.f('ix_payment_invoice_provider'), table_name='payment')
    # ### end Alembic commands ###
