"""empty message

Revision ID: ff2b240c47ed
Revises: 6520076ff89c
Create Date: 2019-01-25 09:49:16.394939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2b240c47ed'
down_revision = '6520076ff89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('invoice_provider', sa.String(length=5), nullable=False))
    op.add_column('payment', sa.Column('invoice_reciever', sa.String(length=5), nullable=False))
    op.drop_column('payment', 'number_invoice_reciever')
    op.drop_column('payment', 'number_invoice_provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('number_invoice_provider', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('number_invoice_reciever', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.drop_column('payment', 'invoice_reciever')
    op.drop_column('payment', 'invoice_provider')
    # ### end Alembic commands ###
